#pragma checksum "..\..\..\..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "766081D3F2EBAAC9617BC21D68A8FBAB4D75B2E9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ICSharpCode.AvalonEdit;
using ICSharpCode.AvalonEdit.Editing;
using ICSharpCode.AvalonEdit.Highlighting;
using ICSharpCode.AvalonEdit.Rendering;
using ICSharpCode.AvalonEdit.Search;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RblxExecutorUI {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 467 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ViewDashboard;
        
        #line default
        #line hidden
        
        
        #line 570 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl UpdatesList;
        
        #line default
        #line hidden
        
        
        #line 608 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ViewEditor;
        
        #line default
        #line hidden
        
        
        #line 622 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TabBarPanel;
        
        #line default
        #line hidden
        
        
        #line 687 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ICSharpCode.AvalonEdit.TextEditor Editor;
        
        #line default
        #line hidden
        
        
        #line 699 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse StatusIndicator;
        
        #line default
        #line hidden
        
        
        #line 701 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock InjectionStatus;
        
        #line default
        #line hidden
        
        
        #line 714 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ViewScriptHub;
        
        #line default
        #line hidden
        
        
        #line 731 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnLocalScripts;
        
        #line default
        #line hidden
        
        
        #line 735 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnBloxScripts;
        
        #line default
        #line hidden
        
        
        #line 761 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SearchPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 764 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SearchBox;
        
        #line default
        #line hidden
        
        
        #line 780 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel LocalScriptsPanel;
        
        #line default
        #line hidden
        
        
        #line 784 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl ScriptHubList;
        
        #line default
        #line hidden
        
        
        #line 817 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel BloxScriptsPanel;
        
        #line default
        #line hidden
        
        
        #line 821 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl BloxScriptsListView;
        
        #line default
        #line hidden
        
        
        #line 875 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BloxLoadingText;
        
        #line default
        #line hidden
        
        
        #line 884 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PaginationBar;
        
        #line default
        #line hidden
        
        
        #line 891 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PageLabel;
        
        #line default
        #line hidden
        
        
        #line 903 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ViewClients;
        
        #line default
        #line hidden
        
        
        #line 924 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image ClientAvatarImage;
        
        #line default
        #line hidden
        
        
        #line 926 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ClientAccountName;
        
        #line default
        #line hidden
        
        
        #line 930 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ClientPidText;
        
        #line default
        #line hidden
        
        
        #line 934 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ClientBadgeBg;
        
        #line default
        #line hidden
        
        
        #line 939 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse ClientStatusDot;
        
        #line default
        #line hidden
        
        
        #line 941 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ClientStatusBadge;
        
        #line default
        #line hidden
        
        
        #line 955 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ViewSettings;
        
        #line default
        #line hidden
        
        
        #line 985 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SettingsGeneral;
        
        #line default
        #line hidden
        
        
        #line 1054 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleAutoAttach;
        
        #line default
        #line hidden
        
        
        #line 1063 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SettingsIntegrations;
        
        #line default
        #line hidden
        
        
        #line 1079 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleDiscordRPC;
        
        #line default
        #line hidden
        
        
        #line 1094 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleConsoleSwitch;
        
        #line default
        #line hidden
        
        
        #line 1110 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleNotifSound;
        
        #line default
        #line hidden
        
        
        #line 1124 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleSidebarCount;
        
        #line default
        #line hidden
        
        
        #line 1139 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleTaskbarCount;
        
        #line default
        #line hidden
        
        
        #line 1149 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SettingsStartup;
        
        #line default
        #line hidden
        
        
        #line 1165 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleRestorePage;
        
        #line default
        #line hidden
        
        
        #line 1201 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SettingsAppearance;
        
        #line default
        #line hidden
        
        
        #line 1217 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleMinimap;
        
        #line default
        #line hidden
        
        
        #line 1232 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleWordWrap;
        
        #line default
        #line hidden
        
        
        #line 1248 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleLineNumbers;
        
        #line default
        #line hidden
        
        
        #line 1260 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SettingsWindow;
        
        #line default
        #line hidden
        
        
        #line 1276 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleTray;
        
        #line default
        #line hidden
        
        
        #line 1290 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ToggleSavePos;
        
        #line default
        #line hidden
        
        
        #line 1305 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border LoadingOverlay;
        
        #line default
        #line hidden
        
        
        #line 1323 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LoadingText;
        
        #line default
        #line hidden
        
        
        #line 1332 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border NotificationBox;
        
        #line default
        #line hidden
        
        
        #line 1339 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path NotificationIcon;
        
        #line default
        #line hidden
        
        
        #line 1342 "..\..\..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock NotificationText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Syntax Executor;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 2:
            
            #line 311 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.TitleBar_MouseDown);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 351 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Dashboard);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 363 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Editor);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 375 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_ScriptHub);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 387 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Clients);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 400 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Settings);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 429 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Minimize_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 430 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Maximize_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 431 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Close_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.ViewDashboard = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            
            #line 490 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenWebsite_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 514 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DownloadLatest_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 539 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.JoinDiscord_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.UpdatesList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 16:
            this.ViewEditor = ((System.Windows.Controls.Grid)(target));
            return;
            case 17:
            this.TabBarPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 18:
            
            #line 631 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Execute_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 638 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Clear_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 647 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KillRoblox_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 656 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Save_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 665 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Open_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 674 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Attach_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.Editor = ((ICSharpCode.AvalonEdit.TextEditor)(target));
            return;
            case 25:
            this.StatusIndicator = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 26:
            this.InjectionStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.ViewScriptHub = ((System.Windows.Controls.Grid)(target));
            return;
            case 28:
            this.BtnLocalScripts = ((System.Windows.Controls.Button)(target));
            
            #line 732 "..\..\..\..\..\MainWindow.xaml"
            this.BtnLocalScripts.Click += new System.Windows.RoutedEventHandler(this.ShowLocalScripts);
            
            #line default
            #line hidden
            return;
            case 29:
            this.BtnBloxScripts = ((System.Windows.Controls.Button)(target));
            
            #line 736 "..\..\..\..\..\MainWindow.xaml"
            this.BtnBloxScripts.Click += new System.Windows.RoutedEventHandler(this.ShowBloxScripts);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 740 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ScriptBlox_Refresh);
            
            #line default
            #line hidden
            return;
            case 31:
            this.SearchPlaceholder = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.SearchBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 768 "..\..\..\..\..\MainWindow.xaml"
            this.SearchBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.SearchBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 33:
            this.LocalScriptsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 34:
            this.ScriptHubList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 38:
            this.BloxScriptsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 39:
            this.BloxScriptsListView = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 42:
            this.BloxLoadingText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.PaginationBar = ((System.Windows.Controls.Border)(target));
            return;
            case 44:
            
            #line 890 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BloxPrevPage);
            
            #line default
            #line hidden
            return;
            case 45:
            this.PageLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 46:
            
            #line 895 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BloxNextPage);
            
            #line default
            #line hidden
            return;
            case 47:
            this.ViewClients = ((System.Windows.Controls.Grid)(target));
            return;
            case 48:
            this.ClientAvatarImage = ((System.Windows.Controls.Image)(target));
            return;
            case 49:
            this.ClientAccountName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.ClientPidText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 51:
            this.ClientBadgeBg = ((System.Windows.Controls.Border)(target));
            return;
            case 52:
            this.ClientStatusDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 53:
            this.ClientStatusBadge = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 54:
            this.ViewSettings = ((System.Windows.Controls.Grid)(target));
            return;
            case 55:
            
            #line 968 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.SettingsTab_General);
            
            #line default
            #line hidden
            return;
            case 56:
            
            #line 970 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.SettingsTab_Integrations);
            
            #line default
            #line hidden
            return;
            case 57:
            
            #line 972 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.SettingsTab_Startup);
            
            #line default
            #line hidden
            return;
            case 58:
            
            #line 974 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.SettingsTab_Appearance);
            
            #line default
            #line hidden
            return;
            case 59:
            
            #line 976 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.SettingsTab_Window);
            
            #line default
            #line hidden
            return;
            case 60:
            this.SettingsGeneral = ((System.Windows.Controls.Grid)(target));
            return;
            case 61:
            
            #line 1004 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenWorkspace_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            
            #line 1008 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenAutoexec_Click);
            
            #line default
            #line hidden
            return;
            case 63:
            
            #line 1025 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RestartApp_Click);
            
            #line default
            #line hidden
            return;
            case 64:
            
            #line 1041 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Checked += new System.Windows.RoutedEventHandler(this.AlwaysOnTop_Checked);
            
            #line default
            #line hidden
            
            #line 1042 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Unchecked += new System.Windows.RoutedEventHandler(this.AlwaysOnTop_Unchecked);
            
            #line default
            #line hidden
            return;
            case 65:
            this.ToggleAutoAttach = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 66:
            this.SettingsIntegrations = ((System.Windows.Controls.Grid)(target));
            return;
            case 67:
            this.ToggleDiscordRPC = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 68:
            this.ToggleConsoleSwitch = ((System.Windows.Controls.CheckBox)(target));
            
            #line 1097 "..\..\..\..\..\MainWindow.xaml"
            this.ToggleConsoleSwitch.Checked += new System.Windows.RoutedEventHandler(this.ToggleConsole_Checked);
            
            #line default
            #line hidden
            
            #line 1098 "..\..\..\..\..\MainWindow.xaml"
            this.ToggleConsoleSwitch.Unchecked += new System.Windows.RoutedEventHandler(this.ToggleConsole_Unchecked);
            
            #line default
            #line hidden
            return;
            case 69:
            this.ToggleNotifSound = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 70:
            this.ToggleSidebarCount = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 71:
            this.ToggleTaskbarCount = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 72:
            this.SettingsStartup = ((System.Windows.Controls.Grid)(target));
            return;
            case 73:
            this.ToggleRestorePage = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 74:
            
            #line 1184 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SetDefaultPage_Click);
            
            #line default
            #line hidden
            return;
            case 75:
            
            #line 1187 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SetDefaultPage_Click);
            
            #line default
            #line hidden
            return;
            case 76:
            
            #line 1190 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SetDefaultPage_Click);
            
            #line default
            #line hidden
            return;
            case 77:
            
            #line 1193 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SetDefaultPage_Click);
            
            #line default
            #line hidden
            return;
            case 78:
            this.SettingsAppearance = ((System.Windows.Controls.Grid)(target));
            return;
            case 79:
            this.ToggleMinimap = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 80:
            this.ToggleWordWrap = ((System.Windows.Controls.CheckBox)(target));
            
            #line 1235 "..\..\..\..\..\MainWindow.xaml"
            this.ToggleWordWrap.Checked += new System.Windows.RoutedEventHandler(this.WordWrap_Checked);
            
            #line default
            #line hidden
            
            #line 1236 "..\..\..\..\..\MainWindow.xaml"
            this.ToggleWordWrap.Unchecked += new System.Windows.RoutedEventHandler(this.WordWrap_Unchecked);
            
            #line default
            #line hidden
            return;
            case 81:
            this.ToggleLineNumbers = ((System.Windows.Controls.CheckBox)(target));
            
            #line 1252 "..\..\..\..\..\MainWindow.xaml"
            this.ToggleLineNumbers.Checked += new System.Windows.RoutedEventHandler(this.LineNumbers_Checked);
            
            #line default
            #line hidden
            
            #line 1253 "..\..\..\..\..\MainWindow.xaml"
            this.ToggleLineNumbers.Unchecked += new System.Windows.RoutedEventHandler(this.LineNumbers_Unchecked);
            
            #line default
            #line hidden
            return;
            case 82:
            this.SettingsWindow = ((System.Windows.Controls.Grid)(target));
            return;
            case 83:
            this.ToggleTray = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 84:
            this.ToggleSavePos = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 85:
            this.LoadingOverlay = ((System.Windows.Controls.Border)(target));
            return;
            case 86:
            this.LoadingText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 87:
            this.NotificationBox = ((System.Windows.Controls.Border)(target));
            return;
            case 88:
            this.NotificationIcon = ((System.Windows.Shapes.Path)(target));
            return;
            case 89:
            this.NotificationText = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 173 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TabClose_Click);
            
            #line default
            #line hidden
            break;
            case 35:
            
            #line 797 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ExecuteScriptHub_Click);
            
            #line default
            #line hidden
            break;
            case 36:
            
            #line 801 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CopyScriptHub_Click);
            
            #line default
            #line hidden
            break;
            case 37:
            
            #line 805 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteScriptHub_Click);
            
            #line default
            #line hidden
            break;
            case 40:
            
            #line 862 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BloxLoad_Click);
            
            #line default
            #line hidden
            break;
            case 41:
            
            #line 866 "..\..\..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BloxCopy_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

