//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Brilliant Team")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© 2026 Brilliant Team")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Brilliant Executor - Premium Roblox Execution Engine with ScriptBlox Integration")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.0.0.0+7ed6c29adb302b585682279a44d1e7792fe5ce61")]
[assembly: System.Reflection.AssemblyProductAttribute("Brilliant Executor")]
[assembly: System.Reflection.AssemblyTrademarkAttribute("Brilliant")]
[assembly: System.Reflection.AssemblyTitleAttribute("Brilliant Executor")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.0.0.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Generated by the MSBuild WriteCodeFragment class.

